using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

namespace NovelForge.Runtime.Tests
{
    public class ScriptCompilerLocalizationTests
    {
        [Test]
        public void DialogueLine_WithExplicitIdTag_UsesThatIdForTranslationLookup()
        {
            var script = new ScriptCompiler().Compile("Alice: Hello! @custom_greet\n");
            var dialogue = new RecordingDialoguePresenter();
            var context = new StoryContext { Dialogue = dialogue, Localization = LocalizationTable.FromJson("{\"custom_greet\": \"Привет!\"}") };

            CoroutineTestUtil.RunToCompletion(script.Commands[0].Execute(context, new StoryPointer()));

            Assert.AreEqual("Привет!", dialogue.Calls[0].text);
        }

        [Test]
        public void DialogueLine_WithoutIdTag_GeneratesLabelAndOrdinalId()
        {
            var script = new ScriptCompiler().Compile("label greet\nAlice: Hello!\n");
            var dialogue = new RecordingDialoguePresenter();
            var context = new StoryContext { Dialogue = dialogue, Localization = LocalizationTable.FromJson("{\"greet_1\": \"Привет!\"}") };

            CoroutineTestUtil.RunToCompletion(script.Commands[0].Execute(context, new StoryPointer()));

            Assert.AreEqual("Привет!", dialogue.Calls[0].text);
        }

        [Test]
        public void DialogueLine_BeforeAnyLabel_UsesStartPseudoLabelForAutoId()
        {
            var script = new ScriptCompiler().Compile("Alice: Hello!\n");
            var dialogue = new RecordingDialoguePresenter();
            var context = new StoryContext { Dialogue = dialogue, Localization = LocalizationTable.FromJson("{\"_start_1\": \"Привет!\"}") };

            CoroutineTestUtil.RunToCompletion(script.Commands[0].Execute(context, new StoryPointer()));

            Assert.AreEqual("Привет!", dialogue.Calls[0].text);
        }

        [Test]
        public void Label_ResetsAutoIdOrdinalForFollowingLines()
        {
            var script = new ScriptCompiler().Compile("label first\nAlice: One\nAlice: Two\nlabel second\nAlice: Three\n");
            var dialogue = new RecordingDialoguePresenter();
            var localization = LocalizationTable.FromJson(@"{
                ""first_1"": ""Один"",
                ""first_2"": ""Два"",
                ""second_1"": ""Три""
            }");
            var context = new StoryContext { Dialogue = dialogue, Localization = localization };
            var controller = new PlaybackController(script, context);

            CoroutineTestUtil.RunToCompletion(controller.RunAll());

            CollectionAssert.AreEqual(new[] { "Один", "Два", "Три" }, dialogue.Calls.ConvertAll(c => c.text));
        }

        [Test]
        public void ChoiceOption_ExplicitAndAutoIdsShareOrdinalCounterWithDialogueLines()
        {
            const string source =
                "label pick\n" +
                "choice\n" +
                "  \"Yes\" @yes_opt -> yes_label\n" +
                "  \"No\" -> no_label\n" +
                "label yes_label\n" +
                "return\n" +
                "label no_label\n" +
                "return\n";
            var script = new ScriptCompiler().Compile(source);
            var choices = new RecordingChoicePresenter { NextSelection = 0 };
            var localization = LocalizationTable.FromJson("{\"yes_opt\": \"Да\", \"pick_2\": \"Нет\"}");
            var context = new StoryContext { Choices = choices, Localization = localization };

            CoroutineTestUtil.RunToCompletion(script.Commands[0].Execute(context, new StoryPointer()));

            CollectionAssert.AreEqual(new[] { "Да", "Нет" }, choices.Calls[0]);
        }

        [Test]
        public void DuplicateExplicitId_ThrowsParseException()
        {
            var ex = Assert.Throws<ParseException>(() =>
                new ScriptCompiler().Compile("label dup\nAlice: Hello! @dup_id\nAlice: Hi again! @dup_id\n"));

            StringAssert.Contains("dup_id", ex.Message);
        }

        [Test]
        public void ExplicitIdCollidingWithAutoGeneratedId_ThrowsParseException()
        {
            var ex = Assert.Throws<ParseException>(() =>
                new ScriptCompiler().Compile("label dup2\nAlice: First auto line.\nAlice: Second line! @dup2_1\n"));

            StringAssert.Contains("dup2_1", ex.Message);
        }

        [Test]
        public void FullScript_WithMixedAutoAndExplicitIds_PartialTranslation_ResolvesThroughPlaybackController()
        {
            const string source = @"
label opening
  Alice: Hello there! @greeting
  Alice: How are you?

  choice
    ""Good, thanks!"" -> good_path
    ""Not great..."" @choice_bad -> bad_path

label good_path
  Alice: Glad to hear it!
  jump the_end

label bad_path
  Alice: What happened?
  jump the_end

label the_end
  Alice: The end.
";
            var script = new ScriptCompiler().Compile(source);
            var dialogue = new RecordingDialoguePresenter();
            var choices = new RecordingChoicePresenter { NextSelection = 1 };
            var localization = LocalizationTable.FromJson(@"{
                ""greeting"": ""Привет!"",
                ""opening_2"": ""Как дела?"",
                ""opening_3"": ""Хорошо, спасибо!"",
                ""choice_bad"": ""Не очень..."",
                ""good_path_1"": ""Приятно слышать!"",
                ""the_end_1"": ""Конец.""
            }");
            var context = new StoryContext { Dialogue = dialogue, Choices = choices, Localization = localization };
            var controller = new PlaybackController(script, context);

            LogAssert.Expect(LogType.Warning, "NovelForge: no translation for line id 'bad_path_1' — falling back to source text.");
            CoroutineTestUtil.RunToCompletion(controller.RunAll());

            CollectionAssert.AreEqual(new[] { "Хорошо, спасибо!", "Не очень..." }, choices.Calls[0]);
            CollectionAssert.AreEqual(
                new[] { "Привет!", "Как дела?", "What happened?", "Конец." },
                dialogue.Calls.ConvertAll(c => c.text));
            Assert.IsTrue(controller.IsFinished);
        }
    }
}
